### ISSUE TITLE
Ruby Group Capstone Project - Catalog of My Things

### ISSUE THREAD

**Issue by lily4178993** [rmiyoyo/catalogue-of-my-things#39]
### GitHub Repository Link
[Link to the GitHub Project](https://github.com/rmiyoyo/catalogue-of-my-things/projects/2)

### Team Information
- Number of Team Members: **3**
- Team Members:
  - Team member 1: [@richie1988](https://github.com/richie1988)
  - Team member 2: [@lily4178993](https://github.com/lily4178993)
  - Team member 3: [@rmiyoyo](https://github.com/rmiyoyo)

### Tasks Assignment
- Team member 1 @richie1988 : 
    - #34  
    - #19 
    - #18 
    - #17 
    - #16  
    - #15 
    - #14
- Team member 2 @lily4178993 : 
    - #33 
    - #25 
    - #24  
    - #23 
    - #22 
    - #21 
    - #20 
- Team member 3 @rmiyoyo :
    -  #32 
    - #31 
    - #30 
    - #29 
    - #28 
    - #27 
    - #26 
### Additional Notes
- Please review our project kanban board and provide feedback.
- Feel free to reach out if you have any questions or need further clarification.

**Comment by cynthiainga** [comment]
Hi @lily4178993, @richie1988 & @rmiyoyo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] Each card on the board has a descriptive title and a description of the task ✔️ 
- [ ] All cards are assigned to team members ✔️ 

## Required Changes ♻️

- [ ] Please kindly make sure that all your card has a number of points in the \[Xpt\] prefix, some of them don’t have a number of points, kindly fix that 🙃 🙃 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Thank you, @cynthiainga, for the review. Your insights were invaluable.

**Comment by danmainah** [comment]
Hi @lily4178993 , @richie1988 and @rmiyoyo , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️  Implemented the changes requested to add points to the cards

 # Required Changes ♻️

- [ ] @Team Great work implementing the changes requested, however you forgot to add points for the card shown below 
![image](https://github.com/rmiyoyo/catalogue-of-my-things/assets/61408860/49a7bc07-814f-41b5-8507-e5114c34b2ef)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rmiyoyo** [comment]
Thank you, @danmainah, for the review. Your insights were invaluable.

## Work Done
- [x] Number of points added to #38.

**Comment by danmainah** [comment]
Hi @lily4178993 , @rmiyoyo and @richie1988 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ Implemented the changes requested to ensure all cards have a number of points indicated on the title.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
